# Generated by Django 4.0.3 on 2022-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('url', models.URLField(null=True)),
                ('contact_phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('store_address', models.CharField(max_length=150)),
                ('work_schedule', models.CharField(max_length=150)),
                ('services', models.CharField(choices=[('Sale', 'Sale equipment and accessories'), ('Rent', 'Rent equipment and accessories'), ('Sale & rent', 'Sale & rent equipment and accessories'), ('Other', 'Other')], max_length=11)),
            ],
        ),
    ]
