# Generated by Django 4.0.3 on 2022-04-28 06:55

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentstores',
            name='img',
            field=models.ImageField(blank='true', null=True, upload_to='stores_images/', verbose_name='stores_images/'),
        ),
        migrations.AlterField(
            model_name='equipmentstores',
            name='contact_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
