# Generated by Django 4.0.3 on 2022-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_stores', '0002_equipmentstores_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentstores',
            old_name='contact_phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='equipmentstores',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
