# Generated by Django 4.0.3 on 2022-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_stores', '0003_rename_contact_phone_equipmentstores_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentstores',
            old_name='about',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='equipmentstores',
            name='services',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Sale & rent', 'Sale & rent'), ('Other', 'Other')], max_length=11),
        ),
    ]
