# Generated by Django 4.0.4 on 2022-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_stores', '0004_rename_about_equipmentstores_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentstores',
            name='slug',
            field=models.SlugField(default='freeride', unique=True),
            preserve_default=False,
        ),
    ]
