# Generated by Django 4.0.4 on 2022-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_stores', '0005_alter_equipmentstores_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstores',
            name='service',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('sale|Rent', 'Sale|Rent'), ('other', 'Other')], max_length=11, null=True),
        ),
    ]
