# Generated by Django 4.0.4 on 2022-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'UAH')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='food',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RO(room only)'), (2, 'HB(half board)'), (3, 'FB(full board)'), (4, 'AI(all inclusive)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='tours',
            name='residence',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Camp'), (2, 'Camp|Hotel'), (3, 'Hotel')], max_length=10),
        ),
    ]
