# Generated by Django 4.0.4 on 2022-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tours_currency_alter_tours_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'UAH')], null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='food',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RO(room only)'), (2, 'HB(half board)'), (3, 'FB(full board)'), (4, 'AI(all inclusive)')], null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='residence',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Camp'), (2, 'Camp|Hotel'), (3, 'Hotel')], null=True),
        ),
    ]
