# Generated by Django 4.0.3 on 2022-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_organisation_name_bookmarks_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
