# Generated by Django 4.0.4 on 2022-06-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tours_currency_alter_tours_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(related_name='tour_category', to='tours.category'),
        ),
    ]
