# Generated by Django 4.0.4 on 2022-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tours_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='food',
            field=models.PositiveSmallIntegerField(choices=[('room only', 'RO(room only)'), ('half board', 'HB(half board)'), ('full board', 'FB(full board)'), ('all inclusive', 'AI(all inclusive)')], null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='residence',
            field=models.PositiveSmallIntegerField(choices=[('camp', 'Camp'), ('camp|hotel', 'Camp|Hotel'), ('hotel', 'Hotel')], null=True),
        ),
    ]
