# Generated by Django 4.0.4 on 2022-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tours_currency_alter_tours_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='currency',
            field=models.CharField(choices=[('uah', 'UAH')], max_length=3, null=True),
        ),
    ]
