# Generated by Django 4.0.4 on 2022-06-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tours_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
