# Generated by Django 4.0.4 on 2022-06-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tours_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcomments',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
