# Generated by Django 4.0.4 on 2022-06-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tourcomments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourcomments'),
        ),
    ]
