# Generated by Django 4.0.4 on 2022-06-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_alter_tourcomments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.organisationscomment'),
        ),
    ]
