# Generated by Django 4.0.4 on 2022-06-30 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0012_organisationscomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcomments',
            name='author',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
