# Generated by Django 4.0.4 on 2022-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='subscribe_cat',
            field=models.ManyToManyField(blank=True, related_name='subscribes_cat', to='tours.category'),
        ),
    ]
