# Generated by Django 4.0.4 on 2022-06-21 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration_authorisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('moderate_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вподобайка',
                'verbose_name_plural': 'Вподобайки',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категорії новин')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('url', models.URLField(null=True)),
                ('video', models.CharField(max_length=350, null=True)),
                ('news_img', models.ImageField(blank='true', null=True, upload_to='images/', verbose_name='image')),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='news_blog.newscategory', verbose_name='Категорії')),
                ('comment', models.ManyToManyField(related_name='comment_news', through='news_blog.Comments', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='liked_news', through='news_blog.Likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.AddField(
            model_name='likes',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.news'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='article_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_blog.news'),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
