# Generated by Django 4.0.3 on 2022-04-22 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=250, verbose_name='news_topic')),
                ('news_text', models.TextField(verbose_name='news_text')),
                ('source_link', models.URLField(null=True)),
                ('author', models.CharField(max_length=80, null=True, verbose_name='news_author')),
                ('video', models.CharField(max_length=350, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('news_img', models.ImageField(blank='true', null=True, upload_to='images/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100, verbose_name='news_categories')),
            ],
        ),
        migrations.CreateModel(
            name='UserNewsRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('bookmarks', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Nice'), (5, 'Amazing')])),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='readers',
            field=models.ManyToManyField(through='news_blog.UserNewsRelated', to=settings.AUTH_USER_MODEL),
        ),
    ]
