# Generated by Django 4.0.3 on 2022-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='topic',
            new_name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
