# Generated by Django 4.0.4 on 2022-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
