# Generated by Django 4.0.3 on 2022-04-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0002_rename_topic_news_name_news_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='source_link',
            new_name='url',
        ),
    ]
