# Generated by Django 4.0.3 on 2022-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0004_bookmarks_comments_likes_ratings_remove_news_readers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='news',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
