# Generated by Django 4.0.4 on 2022-06-23 19:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, help_text='Максимум 200 символів', max_length=160, null=True, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='В форматі(+12(345)6789 123) ', max_length=128, region=None, verbose_name='Номер телефону'),
        ),
    ]
