# Generated by Django 4.0.3 on 2022-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
